import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {


    /**
     * [kotlinx-serialization-runtime-native website](0.11.1-1.3.40-eap-107)
     */
    const val kotlinx_serialization_runtime_native: String =
        "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:" +
                Versions.kotlinx_serialization_runtime_native

    /**
     * [ktor-client-serialization-iosx64 website](https://github.com/ktorio/ktor)
     */
    const val ktor_client_serialization_iosx64: String =
        "io.ktor:ktor-client-serialization-iosx64:" + Versions.ktor_client_serialization_iosx64

    /**
     * [ktor-client-json-native website](1.2.2)
     */
    const val ktor_client_json_native: String = "io.ktor:ktor-client-json-native:" +
            Versions.ktor_client_json_native

    /**
     * [ktor-client-ios website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_ios: String = "io.ktor:ktor-client-ios:" +
            Versions.io_ktor_ktor_client_ios

    /**
     * [kotlinx-coroutines-core-native website](1.2.2)
     */
    const val kotlinx_coroutines_core_native: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:" +
                Versions.kotlinx_coroutines_core_native

    /**
     * [ktor-client-android website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_android: String = "io.ktor:ktor-client-android:" +
            Versions.io_ktor_ktor_client_android

    /**
     * [ktor-client-okhttp website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_okhttp: String = "io.ktor:ktor-client-okhttp:" +
            Versions.io_ktor_ktor_client_okhttp

    /**
     * [ktor-client-json-jvm website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_json_jvm: String = "io.ktor:ktor-client-json-jvm:" +
            Versions.io_ktor_ktor_client_json_jvm

    /**
     * [ktor-client-core-jvm website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_core_jvm: String = "io.ktor:ktor-client-core-jvm:" +
            Versions.io_ktor_ktor_client_core_jvm

    /**
     * [kotlinx-serialization-runtime website](https://github.com/Kotlin/kotlinx.serialization)
     */
    const val kotlinx_serialization_runtime: String =
        "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
                Versions.kotlinx_serialization_runtime

    /**
     * [ktor-client-serialization-jvm website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_serialization_jvm: String =
        "io.ktor:ktor-client-serialization-jvm:" +
                Versions.io_ktor_ktor_client_serialization_jvm

    /**
     * [kotlin-stdlib website](https://kotlinlang.org/)
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.kotlin_stdlib


    /**
     * [ktor-client-serialization website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_serialization: String = "io.ktor:ktor-client-serialization:" +
            Versions.io_ktor_ktor_client_serialization

    /**
     * [ktor-client-json website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_json: String = "io.ktor:ktor-client-json:" +
            Versions.io_ktor_ktor_client_json

    /**
     * [ktor-client-core website](https://github.com/ktorio/ktor)
     */
    const val io_ktor_ktor_client_core: String = "io.ktor:ktor-client-core:" +
            Versions.io_ktor_ktor_client_core

    /**
     * [kotlinx-serialization-runtime-common
     * website](https://github.com/Kotlin/kotlinx.serialization)
     */
    const val kotlinx_serialization_runtime_common: String =
        "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:" +
                Versions.kotlinx_serialization_runtime_common

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines)
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.kotlinx_coroutines_core

    /**
     * [kotlinx-coroutines-core-common website](https://github.com/Kotlin/kotlinx.coroutines)
     */
    const val kotlinx_coroutines_core_common: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:" +
                Versions.kotlinx_coroutines_core_common

    /**
     * [kotlin-stdlib-common website](https://kotlinlang.org/)
     */
    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:" +
            Versions.kotlin_stdlib_common

    /**
     * [material website](http://developer.android.com/tools/extras/support-library.html) */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * [core-testing website](https://developer.android.com/topic/libraries/architecture/index.html) */
    const val core_testing: String = "android.arch.core:core-testing:" + Versions.core_testing

    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * [cardview website](http://developer.android.com/tools/extras/support-library.html) */
    const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

    /**
     * [constraintlayout website](http://tools.android.com) */
    const val constraintlayout: String =
            "androidx.constraintlayout:constraintlayout:" + Versions.constraintlayout

    /**
     * [core-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "androidx.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * [junit website](https://developer.android.com/testing) */
    const val androidx_test_ext_junit: String =
            "androidx.test.ext:junit:" + Versions.androidx_test_ext_junit

    /**
     * [uiautomator website](https://developer.android.com/testing) */
    const val uiautomator: String = "androidx.test.uiautomator:uiautomator:" + Versions.uiautomator

    /**
     * [rules website](https://developer.android.com/testing) */
    const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test

    /**
     * [runner website](https://developer.android.com/testing) */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "com.android.tools.build:gradle:" + Versions.com_android_tools_build_gradle

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [retrofit2-kotlin-coroutines-adapter website](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/) */
    const val retrofit2_kotlin_coroutines_adapter: String =
            "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:" + Versions.retrofit2_kotlin_coroutines_adapter

    /**
     * [logging-interceptor website](https://github.com/square/okhttp) */
    const val logging_interceptor: String =
            "com.squareup.okhttp3:logging-interceptor:" + Versions.com_squareup_okhttp3

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * [converter-gson website](https://github.com/square/retrofit/) */
    const val converter_gson: String =
            "com.squareup.retrofit2:converter-gson:" + Versions.com_squareup_retrofit2

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String =
            "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

    const val arrow_core: String = "io.arrow-kt:arrow-core:" + Versions.arrow_core

    /**
     * [mockk-android website](http://mockk.io) */
    const val mockk_android: String = "io.mockk:mockk-android:" + Versions.io_mockk

    /**
     * [mockk website](http://mockk.io) */
    const val mockk: String = "io.mockk:mockk:" + Versions.io_mockk

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit_junit: String = "junit:junit:" + Versions.junit_junit

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.kotlinx_coroutines_android

    const val koin_android_viewmodel: String =
            "org.koin:koin-android-viewmodel:" + Versions.org_koin

    /**
     * [extensions website](https://developer.android.com/topic/libraries/architecture/index.html) */
    const val android_arch_lifecycle_extensions: String =
        "android.arch.lifecycle:extensions:" + Versions.android_arch_lifecycle_extensions

    const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin
}
