import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.13.0"
             // available: "0.20.0-1.4-M1-release-99"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.5"
             // available: "1.3.5-1.4-M1-release-99"

    const val com_squareup_retrofit2: String = "2.5.0" // available: "2.8.1"

    const val com_squareup_okhttp3: String = "4.0.0" // available: "4.4.1"

    const val org_koin: String = "2.0.1" // available: "2.1.5"

    const val io_ktor: String = "1.3.1" // available: "1.3.2-1.4-M1-release-99"

    const val android_arch_lifecycle_extensions: String = "1.1.1"

    const val com_android_tools_build_gradle: String = "3.6.1"

    const val org_jetbrains_kotlin_native_cocoapods_gradle_plugin: String = "1.3.61"
             // available: "1.4-M1-release-101"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlin_scripting_compiler_embeddable: String = "1.3.61"
             // available: "1.4-M1-release-101"

    const val kotlin_annotation_processing_gradle: String = "1.3.61"
             // available: "1.4-M1-release-101"

    const val retrofit2_kotlin_coroutines_adapter: String = "0.9.2"

    const val kotlin_android_extensions_runtime: String = "1.3.61"
             // available: "1.4-M1-release-101"

    const val kotlin_test_annotations_common: String = "1.3.61"
             // available: "1.4-M1-release-101"

    const val kotlin_serialization_unshaded: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_android_extensions: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_gradle_plugin: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_serialization: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_stdlib_common: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_stdlib_jdk7: String = "1.3.50" // available: "1.4-M1-release-101"

    const val kotlin_test_common: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_test_junit: String = "1.3.61" // available: "1.4-M1-release-101"

    const val constraintlayout: String = "2.0.0-beta4"

    const val kotlin_stdlib: String = "1.3.61" // available: "1.4-M1-release-101"

    const val kotlin_test: String = "1.3.61" // available: "1.4-M1-release-101"

    const val lint_gradle: String = "26.6.1"

    const val arrow_core: String = "0.8.1"

    const val appcompat: String = "1.1.0-rc01" // available: "1.1.0"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.0.2" // available: "1.2.0"

    const val material: String = "1.0.0" // available: "1.1.0"

    const val aapt2: String = "3.6.1-6040484"

    const val glide: String = "4.2.0" // available: "4.11.0"

    const val mockk: String = "1.9.3"

    /**
     * Current version: "5.6.4"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
